src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommentRepository::class)
 */
class Comment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=120)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=120)
     */
    private $author;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $published_at;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="comments")
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->published_at;
    }

    public function setPublishedAt(\DateTimeInterface $published_at): self
    {
        $this->published_at = $published_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Controller/CoachController.php
<?php

namespace App\Controller;

use DateTime;
use App\Entity\User;
use App\Entity\Comment;
use App\Form\CommentType;
use App\Form\RegistrationType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class CoachController extends AbstractController
{
    /**
     * @Route("/", name="app_home")
     */
    public function home() {

        $coaches = $this->getDoctrine()->getRepository(User::class)->findRandomCoach(6);
        // $form = $this->createFormBuilder()
        // ->setAction($this>generateUrl('app_findcity'))
        // ->add('search' ,TextType::class)
        // ->getForm();
        return $this->render('coach/accueil.html.twig', [
            'coaches'=> $coaches
        ]);
    }
    /**
     * @Route("/coach", name="app_coach")
     */
    public function ListCoach() {
        $coaches = $this->getDoctrine()->getRepository(User::class)->findAll();

        return $this->render('coach/coachList.html.twig', [
            'coaches'=> $coaches,
        ]);
    }
    /**
     * @Route("/view/{id}", name="app_view")
     */
    public function viewCoach(int $id, Request $request, EntityManagerInterface $manager, User $coaches) {
        $details = $this->getDoctrine()->getRepository(User::class);
        $coaches = $details->find($id);

        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);
        if(
            $form->isSubmitted() && $form->isValid()){
                $comment->setPublishedAt(new \DateTime('now'))->setUser($coaches);
                $manager->persist($comment);
                $manager->flush();
                $this->addFlash('success','Votre commentaire a bien été envoyé');
                return $this->redirectToRoute('app_view',[
                    'id'=>$coaches->getId()
                ]);
            }
        
            
        return $this->render('coach/viewcoach.html.twig', [
            'coaches'=> $coaches,
            'commentForm'=> $form->createView()
        ]);
    }

    /**
     * @Route("/mon-compte/update", name="app_update")
     */
    public function update(UserPasswordEncoderInterface $encoder, Request $request,SluggerInterface $slugger ) 
    {
        // Utilisateur non connecté
        if(empty($this->getUser())){
            return $this->redirectToRoute('app_home');
        }
        
        $errors = [];
       
        $em = $this->getDoctrine()->getManager(); // Connexion
        // $this->getUser() contient l'utilisateur actuellement connecté. Je peux donc le passé dans le find()
        $user = $em->getRepository(User::class)->find($this->getUser());

        $form = $this->createForm(RegistrationType::class, $user);

        // Analyse la requête
        $form->handleRequest($request);

        // Vérification du formulaire
        if($form->isSubmitted() && $form->isValid()) {

            $pictureFile = $form->get('picture')->getData();
            // Je vérifie que l'image soit bien uploadé
            if ($pictureFile) {

                // Je récupère le nom original de l'image
                $originalFilename = pathinfo($pictureFile->getClientOriginalName(), PATHINFO_FILENAME);
                // Je nettoie le nom du fichier original, je le slugify pour éviter les caractères accentués , espaces et autres caractères spéciaux
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$pictureFile->guessExtension();

                // Je sauvegarde mon fichier
                try {
                    $pictureFile->move(
                        $this->getParameter('photo_profil_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    //En cas de gros problème (exemple le répertoire d'image n'existe pas)
                }

                // Modifie l ancienne  image dans la bdd
                $user->setPicture($newFilename);
            }


            // $form->get('password')->getData() equivalent de $safe['password']
            if(!empty($form->get('password')->getData())){
                $hash = $encoder->encodePassword($user, $user->getPassword());
                $user->setPassword($hash);
            }
            $em->persist($user);
            $em->flush();

            return $this->redirectToRoute('app_home');
        }

        return $this->render('coach/update.html.twig', [
            'form' => $form->createView(),
            'update' => $user,
            'errors' => $errors
        ]);
    }

    /**
     * @Route("/recherche-coach/{city}", name="app_search")
     */
    public function searchCityCoach(string $city) {
        $coaches = $this->getDoctrine()->getRepository(User::class)->findCityCoach($city);
        
        return $this->render('coach/cityCoach.html.twig', [
            'coaches'=> $coaches,
        ]);
    }
      /**
     * @Route("/recherche-ville", name="app_findcity")
     */
    public function findByCity(Request $request) {

       $searchcity = $request->request->get('search');
       $coaches = $this->getDoctrine()->getRepository(User::class)->findCityCoach($searchcity);
        
        return $this->render('coach/cityCoach.html.twig', [
            'coaches'=> $coaches,
        ]);
    }

    /**
     * @Route("/reservation", name="app_reservation")
     */
    public function reservation() {
        return $this->render('coach/reservation.html.twig');
    }

    #Supprimer les données d'un coach
   /**
     * @Route("/delete/{id}", name="delete_coach")
     */
    public function delete(int $id): Response
    {
        $em = $this->getDoctrine()->getManager(); // Connexion
        $coach = $em->getRepository(User::class)->find($id);

        if(empty($coach)){
            throw $this->createNotFoundException("Le profil n'existe pas");
        }


        if(!empty($_POST)){
            if(isset($_POST['confirm']) && $_POST['confirm'] === 'yes'){

                $this->container->get('security.token_storage')->setToken(null);
                $em->remove($coach);
                $em->flush();

                $this->addFlash('success', 'Votre profil a bien été supprimé');
                return $this->redirectToRoute('app_home');
            }
        }

        return $this->render('coach/delete.html.twig', [
            'coach' => $coach,
        ]);
    }
}

templates/coach/_old_update.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification{% endblock %}

{% block body %}

<div class="row justify-content-center mt-5 mb-5">
    <div class="col-6">
    <h1 class="h2">Mise à jours des informations</h1>
      <form method="post">

      {% if errors.firstName is defined %}
                <div class="btn btn-outline-danger">
                    {{ errors.firstName }} 
                </div>
                {% endif %}
        <div class="mb-3">
            <label for="firstName" class="form-label">Nouveau Prénom</label>
            <input type="text" name="firstName" class="form-control" id="firstName" placeholder="Entrez votre nouvel firstName" value="{{ update.firstName }}">
        </div>

        {% if errors.lastName is defined %}
                <div class="btn btn-outline-danger">
                    {{ errors.lastName }} 
                </div>
                {% endif %}
        <div class="mb-3">
            <label for="lastName" class="form-label">Nouveau Nom</label>
            <input type="text" name="lastName" class="form-control" id="lastName" placeholder="Entrez votre nouvel lastName" value="{{ update.lastName }}">
        </div>

        {% if errors.email is defined %}
                <div class="btn btn-outline-danger">
                    {{ errors.email }} 
                </div>
                {% endif %}
        <div class="mb-3">
            <label for="email" class="form-label">Nouvel Email</label>
            <input type="text" name="email" class="form-control" id="email" placeholder="Entrez votre nouvel email" value="{{ update.email }}">
        </div>

        {% if errors.age is defined %}
                <div class="btn btn-outline-danger">
                    {{ errors.age }} 
                </div>
                {% endif %}
        <div class="mb-3">
            <label for="age" class="form-label">Nouvel Age</label>
            <input type="number" name="age" class="form-control" id="age" placeholder="Entrez votre nouvel age" value="{{ update.age }}">
        </div>

        {% if errors.password is defined %}
                <div class="btn btn-outline-danger">
                    {{ errors.password }} 
                </div>
                {% endif %}
        <div class="mb-3">
            <label for="password" class="form-label">Nouveau Mot de Passe</label>
            <input type="password" name="password" class="form-control" id="password" placeholder="Entrez votre nouveau mot de passe" value="">
            <p clas="text-muted small">Si vous ne souhaitez pas changer votre mot de passe, vous pouvez laisser ce champ vide</p>
        </div>

        {% if errors.city is defined %}
                <div class="btn btn-outline-danger">
                    {{ errors.city }} 
                </div>
                {% endif %}
        <div class="mb-3">
            <label for="city" class="form-label">Nouvelle localisation</label>
            <input type="text" name="city" class="form-control" id="city" placeholder="Entrez votre ville" value="{{ update.city }}">
        </div>

        {% if errors.description is defined %}
                <div class="btn btn-outline-danger">
                    {{ errors.description }} 
                </div>
                {% endif %}
        <div class="mb-3">
                <label for="description" class="form-label">Nouvelle description</label>
                <textarea name="description" class="form-control" id="description" rows="3" placeholder="Saisissez la nouvelle description de votre profil">{{ update.description }}</textarea>
        </div>

        {% if errors.experience is defined %}
                <div class="btn btn-outline-danger">
                    {{ errors.experience }} 
                </div>
                {% endif %}
        <div class="mb-3">
                <label for="experience" class="form-label">Nouvelle experience</label>
                <textarea name="experience" class="form-control" id="experience" rows="3" placeholder="Saisissez la nouvelle experience de votre profil">{{ update.experience }}</textarea>
        </div>

        {% if errors.education is defined %}
                <div class="btn btn-outline-danger">
                    {{ errors.education }} 
                </div>
                {% endif %}
        <div class="mb-3">
            <label for="education" class="form-label">Nouvelle Formation</label>
            <input type="text" name="education" class="form-control" id="education" placeholder="Entrez vos nouvelles formations" value="{{ update.education }}">
        </div>

        {% if errors.sport is defined %}
                <div class="btn btn-outline-danger">
                    {{ errors.sport }} 
                </div>
                {% endif %}
        <div class="mb-3">
            <label for="sport" class="form-label" >Nouvelle Spécialité</label>
            <input type="text" name="sport" class="form-control" id="sport" placeholder="Entrez vos nouvelles spécialité" value="{{ update.sport }}">
        </div>

        {% if errors.tarif is defined %}
                <div class="btn btn-outline-danger">
                    {{ errors.tarif }} 
                </div>
                {% endif %}
        <div class="mb-3">
            <label for="tarif" class="form-label" >Nouveau Tarif</label>
            <input type="text" name="tarif" class="form-control" id="tarif"  placeholder="Choisissez un autre tarif" value="{{ update.tarif }}">
        </div>
               {% if errors.picture is defined %}
                <div class="btn btn-outline-danger">
                    {{ errors.picture }} 
                </div>
                {% endif %}
        <div class="mb-3">
            <label for="picture" class="form-label" >Nouvelle Image</label>
            <input type="file" name="picture" class="form-control" id="picture"  value="{{ update.picture }}">
        </div>
       
        <button class="btn btn-outline-light text-white bg-dark m-auto rounded-pill bg-light text-dark" type="submit">Mise a jour Coach</button>
        <a href="{{ path('app_home') }}" class="btn btn-outline-light text-white bg-dark m-auto rounded-pill bg-light text-dark">Annuler</a>


    </form>
</div>
</div>

{% endblock %}

templates/coach/accueil.html.twig
{% extends 'base.html.twig' %}

{% block title %}Body challenge!{% endblock %}

{% block body %}
<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://image.shutterstock.com/image-vector/abstract-background-straight-lines-splashes-600w-1184674987.jpg"
        class="d-block w-100" alt="carousel1">
         <h2 class="position-absolute top-50 start-50 translate-middle h1 text-white">Challenge your limite</h2>
      <div class="carousel-caption">
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://image.shutterstock.com/image-vector/abstract-background-straight-lines-splashes-600w-1702964722.jpg" class="d-block w-100 img-fluid" alt="carousel2">
      <h2 class="position-absolute top-50 start-50 translate-middle h1 text-white">Challenge your limite</h2>
    </div>

    <div class="carousel-item">
      <img
        src="https://image.shutterstock.com/shutterstock/photos/1702960783/display_1500/stock-vector-abstract-background-with-straight-lines-and-splashes-in-minimalist-flat-style-vector-suitable-1702960783.jpg"
        class="d-block w-100" alt="carousel3">
      <h2 class="position-absolute top-50 start-50 translate-middle h1 text-white">Challenge your limite</h2>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>


<section class="container mt-5 text-center">
  <a href="{{ path('app_coach') }}"
    class="h1 p-2 text-white bg-dark rounded bg-light text-dark text-decoration-none ">Trouve ton Coach</a>
  <div class="row">
      {% for coach in coaches %}
      <div class="col-md-4 col-sm-12">
        <div class="card text-center mt-5 m-auto" style="width: 18rem;">
          <img src="{{ asset('/uploads/photos_coachs/' ~ coach.picture) }}" alt="Image" class="img-acceuil">
          <div class="card-body">
            <h5 class="card-title">{{ coach.first_name }}, {{ coach.age }} ans</h5>
            <p class="card-text"><a href="{{ path('app_search', {city: coach.city})}}"><i
                  class="las la-map-marker la-2x"></a></i>{{ coach.city }}.</p>
            <p class="card-text"><i class="las la-running la-2x"></i>{{ coach.sport }}</p>
            <p class="card-text">{{ coach.tarif }} €/l'heure</p>
            <a class="btn btn-dark" href="{{ path('app_view', {id: coach.id})}}">Voir le coach</a>
          </div>
        </div>
      </div>
      {% endfor %}
  </div>
</section>
<div class="col-12 mt-5">
  <h2 class="text-center mb-5"><span class="p-2 rounded " id="titre">Nos coaches en France</span></h2>

  <div class="col-5 " id="maCarte"> </div>

</div>


{% endblock %}


{% block javascripts %}
<script>
  var villes = {
    "Paris": {
      "lat": 48.852969,
      "lon": 2.349903
    },
    "Brest": {
      "lat": 48.383,
      "lon": -4.500
    },
    "Quimper": {
      "lat": 48.000,
      "lon": -4.100
    },
    "Bayonne": {
      "lat": 43.500,
      "lon": -1.467
    },
    "Marseille": {
      "lat": 43.296174,
      "lon": 5.362019953
    },
    "Lyon": {
      "lat": 45.737814,
      "lon": 4.832011
    },
    "Toulouse": {
      "lat": 43.604462,
      "lon": 1.444247
    },
    "Bordeaux": {
      "lat": 44.841225,
      "lon": -0.580036
    },
    "Rennes": {
      "lat": 48.111339,
      "lon": -1.68002
    },
    "Caen": {
      "lat": 49.181004,
      "lon": -0.369891
    },
    "Clermont ferand": {
      "lat": 45.777455,
      "lon": 3.081943
    },
    "Nice": {
      "lat": 43.700936,
      "lon": 7.268391
    },
    "Lile": {
      "lat": 50.636565,
      "lon": 3.063528
    },
    "Nancy": {
      "lat": 48.693722,
      "lon": 6.18341
    },
    "Strasbourg": {
      "lat": 48.584614,
      "lon": 7.750713
    },
    "Nante": {
      "lat": 47.213637,
      "lon": -1.554136
    },
    "Lorient": {
      "lat": 47.747734,
      "lon": -3.366091
    },
    "Guingamp": {
      "lat": 48.561848,
      "lon": -3.150201
    },
    "Metz": {
      "lat": 49.119696,
      "lon": 6.176355
    },
    "Angers": {
      "lat": 49.061641,
      "lon": 0.458682
    },
    "Le havre": {
      "lat": 49.493898,
      "lon": 0.107913
    },
    "Dijon": {
      "lat": 47.321581,
      "lon": 5.04147
    },
    "Orleans": {
      "lat": 47.902734,
      "lon": 1.908607
    },
  };
  var tableauMarqueurs = [];

  // On initialise la carte
  var carte = L.map('maCarte').setView([48.852969, 2.349903], 13);

  // On charge les "tuiles"
  L.tileLayer('https://{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png', {
    // Il est toujours bien de laisser le lien vers la source des données
    attribution: 'données © <a href="//osm.org/copyright">OpenStreetMap</a>/ODbL - rendu <a href="//openstreetmap.fr">OSM France</a>',
    minZoom: 1,
    maxZoom: 20
  }).addTo(carte);

  var marqueurs = L.markerClusterGroup();

  var marqueurs = L.markerClusterGroup();

  // On personnalise le marqueur
  var icone = L.icon({
    iconUrl: "images/marqueur.png",
    iconSize: [50, 50],
    iconAnchor: [25, 50],
    popupAnchor: [0, -50]
  })
  // On parcourt les différentes villes
  for (ville in villes) {
    console.log(ville);
    // On crée le marqueur et on lui attribue une popup
    var marqueur = L.marker([villes[ville].lat, villes[ville].lon], {
      icon: icone
    }); //.addTo(carte); Inutile lors de l'utilisation des clusters
    var popupContent = '<p>' + ville + '</p>';
    popupContent += '<br><a href="/recherche-coach/' + ville.toLowerCase() + '">Voir tous les coachs</a>';

    marqueur.bindPopup(popupContent);
    marqueurs.addLayer(marqueur); // On ajoute le marqueur au groupe

    // On ajoute le marqueur au tableau
    tableauMarqueurs.push(marqueur);
  }
  // On regroupe les marqueurs dans un groupe Leaflet
  var groupe = new L.featureGroup(tableauMarqueurs);

  // On adapte le zoom au groupe
  carte.fitBounds(groupe.getBounds().pad(0.5));

  // On adapte le zoom au groupe
  carte.fitBounds(groupe.getBounds().pad(0.5));

  carte.addLayer(marqueurs);
</script>
{% endblock %}

templates/coach/cityCoach.html.twig
{% extends 'base.html.twig' %}

{% block title %}Coach dans votre région{% endblock %}

{% block body %}
<h1 class="text-center">Nos coaches dans votre région</h1>
{% for message in app.flashes('success') %}
<div class="alert alert-success text-center" role="alert">{{ message }}</div>
{% endfor %}

<div class="container">
    <div class="row justify-content-center">
        {% for coach in coaches %}
        <div class="col-md-4 col-sm-12">
            <div class="card text-center mt-5" style="width: 18rem;">
                <img src="{{ asset('/uploads/photos_coachs/' ~ coach.picture) }}" alt="Image">
                <div class="card-body">
                  <h5 class="card-title">{{ coach.first_name }}, {{ coach.age }} ans </h5>
                  <p class="card-text">{{ coach.sport }}.</p>
                  <p class="card-text">{{ coach.city }}.</p>
                  <p class="card-text">{{ coach.tarif }} €/heure</p>
                  <a href="{{ path('app_view', {id: coach.id})}}" class="btn btn-dark m-auto rounded-pill">Voir le coach</a>

        
                </div>
              </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/coach/coachList.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos coaches{% endblock %}

{% block body %}

{% for message in app.flashes('success') %}
<div class="alert alert-success text-center" role="alert">{{ message }}</div>
{% endfor %}

<div class="container">
  <h1 class="text-center mt-5 "><span class="p-2 rounded " id="titre">Nos coaches</span></h1>
  <div class="row">
    {% for coach in coaches %}
    <div class="col-md-4 col-sm-12">
      <div class="card text-center mt-5 rounded-3 m-auto" style="width: 18rem;">
        <img src="{{ asset('/uploads/photos_coachs/' ~ coach.picture) }}" alt="Image">
        <div class="card-body">
          <h5 class="card-title">{{ coach.firstName }}, {{ coach.age }} ans </h5>
          <p class="card-text"><i class="las la-running la-2x"></i>{{ coach.sport }}.</p>
          <p class="card-text"><a href="{{ path('app_search', {city: coach.city})}}"><i
                class="las la-map-marker la-2x"></a></i>{{ coach.city }}.</p>
          <p class="card-text"><i class="las la-coins la-2x"></i>{{ coach.tarif }} €/heure</p>
          <a href="{{ path('app_view', {id: coach.id})}}"
            class="btn btn-outline-light text-white bg-dark m-auto rounded-pill bg-light text-dark">Voir le coach</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>




{% endblock %}

templates/coach/delete.html.twig
{% extends 'base.html.twig' %}

{% block title %}Supprimer votre profil{% endblock %}

{% block body %}
<div class="row justify-content-center">

    <div class="col-6">
        <form method="post">
            <p>Vous êtes sur de vouloir supprimer votre profil </p> 
            


            <p>Attention, la suppression d'un profil est définitive !!</p>


            
            <a href="{{ path('app_home') }}" class="btn btn-outline-secondary">Non, annuler</a>


            <input type="hidden" name="confirm" value="yes">
            <button type="submit" class="btn btn-danger">Oui, je supprime mon profil</button>
        </form>

    </div>
</div>


{% endblock %}

templates/coach/reservation.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}

<img src="https://images7.alphacoders.com/409/thumb-1920-409060.jpg" alt="Chantier" class="img-fluid">

{% endblock %}

templates/coach/viewCoach.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page détails{% endblock %}

{% block body %}
{% for message in app.flashes('success') %}
<div class="alert-success text-center mt-3">
    {{ message }}
</div>
{% endfor %}

<section class="container mt-5 text-center">
    <div>
        <h1 class="fs-6 p-3 mb-5 text-white bg-dark rounded-top rounded-bottom red_view_coach">Nos cours sont
            disponibles durant le
            confinement ❤️ ! C'est le moment de se remettre en forme 💪 et de stimuler son immunité 🍎🍋🥝 pour détruire
            le COVID-19 🔥</h1>
    </div>
    <div class="row">
        <div class="col-12 col-md-4">
            <img src="{{ asset('/uploads/photos_coachs/' ~ coaches.picture) }}" alt="Image" class=" rounded-circle">
            <p>{{ coaches.firstName }}, {{ coaches.age }} ans</p>
            <p class="card-text"><a href="{{ path('app_search', {city: coaches.city})}}"><i
                        class="las la-map-marker la-2x"></a></i>{{ coaches.city }}.</p>
            {# le length permet d'additioner le nombres d'avis sur le coach #}
            <p><a href="#avis">{{ coaches.comments | length }} avis</a></p>
            {% if not app.user %}
            <a href="{{ path('app_login') }}" type="submit"
                class="btn btn-outline-light text-white bg-dark">Connectez-vous</a>
            <a href="{{ path('app_inscription') }}" type="submit"
                class="btn btn-outline-light text-white bg-dark">Inscrivez-vous</a>
            {% else %}
            <a href="https://calendly.com/saintsuperylucas/60min?back=1&month=2021-06" type="submit"
                class="btn btn-outline-light text-white bg-dark">Réserver</a>
            {% endif %}
        </div>
        <div class="col-12 col-md-4">
            <p class="fs-1 m-0"><i class="las la-graduation-cap la-lg"></i></p>
            <h1>Formation</h1>
            <p>{{ coaches.education | nl2br }}</p>
        </div>
        <div class="col-12 col-md-4">
            <p class="fs-1 m-0"><i class="las la-check-circle la-lg"></i></p>
            <h1>Expérience</h1>
            <p>{{ coaches.experience | nl2br }}</p>
        </div>
    </div>
</section>
<section class="container text-center text-white pb-5 mt-5 rounded">
    <div class="description bg-dark">
        <h1 class="pt-5 mb-4">Votre coach vous parle</h1>
        <p class="lh-lg px-5 pb-5">{{ coaches.description | nl2br }}</p>
    </div>
</section>



{% if not app.user %}
<div class="container">
    <p>Pour laisser un commentaire</p>
    <a href="{{ path('app_login') }}" type="submit"
        class="btn btn-outline-light text-white bg-dark text-center">Connectez-vous</a>
    <a href="{{ path('app_inscription') }}" type="submit"
        class="btn btn-outline-light text-white bg-dark text-center">Inscrivez-vous</a>
</div>
{% else %}
<section class="container commentaire mt-5" id="avis">
    <h1>Commentaires :</h1>
    {% for comment in coaches.comments %}
    <hr>
    <h1 class="fs-3">{{ comment.author }}</h1>
    <h2 class="fs-3">{{ comment.title }}</h2>
    <p><em>Publié le {{ comment.publishedAt | date('d/m/Y à H:i') }}</em></p>
    <p>{{ comment.content }}</p>
    {% endfor %}
</section>
<div class="container pb-3 bg-dark">
    {{ form_start(commentForm) }}
    {{ form_row(commentForm.title, {'attr': {'placeholder': "Votre titre"}})}}
    {{ form_row(commentForm.author, {'attr': {'placeholder': "Votre nom"}})}}
    {{ form_row(commentForm.content, {'attr': {'placeholder': "Votre contenu"}})}}

    <button type="submit" class="btn btn-outline-light text-white bg-dark mt-3">Commenter</button>

    {{ form_end(commentForm) }}
</div>
{% endif %}
{% endblock %}